### ISSUE TITLE
Should this repository be under the CHIPS Alliance?

### ISSUE THREAD

**Issue by mithro** [chipsalliance/uvm-verilator#1]
@mgielda / @pgielda / @kgugala / @hzeller - Should this repository be under the CHIPS Alliance?

The description says;
> This is intended for use by:
>  * Any project desiring UVM as a submodule.
>  * All projects using UVM with [Verilator](https://verilator.org/). Note Verilator UVM support is still in development.
>  * The [SymbiFlow sv-tests](https://github.com/SymbiFlow/sv-tests) project.

And sv-tests and Verilator are pretty active under the CHIPS Alliance banner....

**Comment by wsnyder** [comment]
Such a move would make sense to me.

**Comment by mgielda** [comment]
We discussed it at the TSC today and everyone agreed, so we should be doing this soon.

**Comment by kgugala** [comment]
Done
